#Section to define paths for the pre-processing
# This section will be used by the scripts under pre_processing
shared:
  start_date: 2021010100 # 2024010100
  end_date: 2021010123 # 2024010123
  
pre:
  fclen: 24
  vfld_path: "/ec/res4/scratch/nhd/test_data_harp/vfld" # "/ec/res4/scratch/nhd/verification/vfld" # "/ec/res4/scratch/nhd/test_data_harp/vfld"
  vobs_path: "/ec/res4/scratch/nhd/test_data_harp/vobs" #"/ec/res4/scratch/nhd/verification/DMI_data/vobs/DMI" # "/ec/res4/scratch/nhd/test_data_harp/vobs"
  by_vobs_step: "1h"
  vfld_template:  #include one for each model if they are different. 
    - "vfld"
  do_all: TRUE # if true, it will ignore list of parameters and do all that is available in the vfld files
  params:
    - S10m
    - T2m
    - RH2m
    - Pmsl
    - T

#Section to define paths for the verification
# This section will be used by the scripts under verification
verif:
  by_step: "12h"
  fcst_model:
    - testmodel #enea43h22mbr000
  lead_time: seq(0, 24, 1)
  fcst_type: "det" #det or eps
  grps: "lead_time"
  fcst_path: "/ec/res4/scratch/nhd/test_data_harp/FCTABLE"
  obs_path: "/ec/res4/scratch/nhd/test_data_harp/OBSTABLE"
  verif_path: "/ec/res4/scratch/nhd/test_data_harp/output/verif_results"

#Section to define the paths for the output
# This section will be used by the plotting scripts
post:
  plot_output: "/ec/res4/scratch/nhd/test_data_harp/output"
  rds_path: "/ec/res4/scratch/smcd/verif_rds"
#This section if only for the scorecards
scorecards:
  ref_model: FC1
  fcst_model: FC2
  params:
    - T2m
    - S10m
    - RH2m
    - Pmsl
